version: 2
updates:
  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "patch"

  # Server dependencies
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore(server-deps):"
      include: "scope"
    groups:
      nestjs-dependencies:
        patterns:
          - "@nestjs/*"
        update-types:
          - "minor"
          - "patch"
      typeorm-dependencies:
        patterns:
          - "typeorm"
          - "pg"
          - "@types/pg"
        update-types:
          - "minor"
          - "patch"

  # Client dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore(client-deps):"
      include: "scope"
    groups:
      angular-dependencies:
        patterns:
          - "@angular/*"
        update-types:
          - "minor"
          - "patch"
      angular-material-dependencies:
        patterns:
          - "@angular/material"
          - "@angular/cdk"
        update-types:
          - "minor"
          - "patch"

  # Shared dependencies
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore(shared-deps):"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore(docker):"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore(docker):"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "chore(actions):"
      include: "scope" 